[global]
excludes = ["template/**"]

[formatter.biome]
command = "biome"
options = [
  "check",
  "--write",
  "--no-errors-on-unmatched",
  "--files-ignore-unknown=true",
]
includes = ["*.css", "*.js", "*.ts", "*.json", "*.jsonc"]
excludes = []

[formatter.nixfmt]
command = "nixfmt"
options = []
includes = ["*.nix"]
excludes = []

[formatter.taplo]
command = "taplo"
options = ["format"]
includes = ["*.toml"]
excludes = []
